import {
	ColorModeScript,
	UIProvider,
	colorModeManager,
} from "@yamada-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ColorModeScript type="cookie" nonce="testing" />

				<UIProvider colorModeManager={{ ...colorModeManager }.cookieStorage}>
					{children}
				</UIProvider>
			</body>
		</html>
	);
}
